#BleeposAuthTimer v2.0

#The amount of time in seconds we allow the player to login / register
time: 60

#The message we want to send when they take too long to login.
message: '&6Took too long to login.'

#The message we want above the hotbar. Use {time} for a placeholder for the time elapsed
msg: '&6&lPlease login or register to play. &4&l{time}'

#Should we freeze the player in place?
freeze:
  freeze: true
  world: 'world_the_end'
  x: 200
  y: 256
  z: 200

#Should we force the players gamemode?
gamemode:
  force: true
  gamemode: 'spectator'

#Should we prevent players from chatting?
prevent-chat: true

#Should we prevent commands?
prevent-commands: true

#What commands should we keep available?
enabled-cmds:
  - '/l'
  - '/register'
  - '/login'

#Should we hide join and leave messages?
hide-join-messages: true

#Do we want to play the level up sound to the player every second?
sound: true